[2024-09-20T23:16:29.758-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T23:16:29.764-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_test_dag.ingest_to_druid manual__2024-09-21T02:16:14.948966+00:00 [queued]>
[2024-09-20T23:16:29.770-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_test_dag.ingest_to_druid manual__2024-09-21T02:16:14.948966+00:00 [queued]>
[2024-09-20T23:16:29.771-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-20T23:16:29.781-0300] {taskinstance.py:2888} INFO - Executing <Task(DruidOperator): ingest_to_druid> on 2024-09-21 02:16:14.948966+00:00
[2024-09-20T23:16:29.786-0300] {standard_task_runner.py:72} INFO - Started process 150795 to run task
[2024-09-20T23:16:29.788-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'spark_test_dag', 'ingest_to_druid', 'manual__2024-09-21T02:16:14.948966+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/exemplodag.py', '--cfg-path', '/tmp/tmpdx93rz69']
[2024-09-20T23:16:29.789-0300] {standard_task_runner.py:105} INFO - Job 25: Subtask ingest_to_druid
[2024-09-20T23:16:29.819-0300] {task_command.py:467} INFO - Running <TaskInstance: spark_test_dag.ingest_to_druid manual__2024-09-21T02:16:14.948966+00:00 [running]> on host marespc
[2024-09-20T23:16:29.850-0300] {abstractoperator.py:778} ERROR - Exception rendering Jinja template for task 'ingest_to_druid', field 'json_index_file'. Template: '/home/thiagomares/Área de trabalho/fluxos_de_trabalho/include/index.json'
Traceback (most recent call last):
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 770, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/thiagomares/Área de trabalho/fluxos_de_trabalho/include/index.json
[2024-09-20T23:16:29.851-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3114, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3533, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1419, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 770, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/thiagomares/Área de trabalho/fluxos_de_trabalho/include/index.json
[2024-09-20T23:16:29.857-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_test_dag, task_id=ingest_to_druid, run_id=manual__2024-09-21T02:16:14.948966+00:00, execution_date=20240921T021614, start_date=20240921T021629, end_date=20240921T021629
[2024-09-20T23:16:29.867-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T23:16:29.867-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task ingest_to_druid (/home/thiagomares/Área de trabalho/fluxos_de_trabalho/include/index.json; 150795)
Traceback (most recent call last):
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3114, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3533, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1419, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 770, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/thiagomares/Área de trabalho/fluxos_de_trabalho/include/index.json
[2024-09-20T23:16:29.881-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-20T23:16:29.891-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T23:16:29.891-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
