[2024-09-23T21:08:55.211-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-23T21:08:55.218-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_test_dag.run_spark_job scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-23T21:08:55.222-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_test_dag.run_spark_job scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-23T21:08:55.222-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-23T21:08:55.232-0300] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): run_spark_job> on 2024-09-23 00:00:00+00:00
[2024-09-23T21:08:55.235-0300] {standard_task_runner.py:72} INFO - Started process 30223 to run task
[2024-09-23T21:08:55.238-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'spark_test_dag', 'run_spark_job', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/exemplodag.py', '--cfg-path', '/tmp/tmpp02vrrwg']
[2024-09-23T21:08:55.239-0300] {standard_task_runner.py:105} INFO - Job 35: Subtask run_spark_job
[2024-09-23T21:08:55.266-0300] {task_command.py:467} INFO - Running <TaskInstance: spark_test_dag.run_spark_job scheduled__2024-09-23T00:00:00+00:00 [running]> on host marespc
[2024-09-23T21:08:55.312-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_test_dag' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-09-23T21:08:55.312-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-23T21:08:55.327-0300] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-09-23T21:08:55.328-0300] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://192.168.18.10:7077 --name spark_test_job --verbose --queue root.default --deploy-mode client ./include/teste.py
[2024-09-23T21:08:56.561-0300] {spark_submit.py:579} INFO - Using properties file: null
[2024-09-23T21:08:56.702-0300] {spark_submit.py:579} INFO - Parsed arguments:
[2024-09-23T21:08:56.703-0300] {spark_submit.py:579} INFO - master                  spark://192.168.18.10:7077
[2024-09-23T21:08:56.703-0300] {spark_submit.py:579} INFO - remote                  null
[2024-09-23T21:08:56.704-0300] {spark_submit.py:579} INFO - deployMode              client
[2024-09-23T21:08:56.704-0300] {spark_submit.py:579} INFO - executorMemory          null
[2024-09-23T21:08:56.704-0300] {spark_submit.py:579} INFO - executorCores           null
[2024-09-23T21:08:56.704-0300] {spark_submit.py:579} INFO - totalExecutorCores      null
[2024-09-23T21:08:56.704-0300] {spark_submit.py:579} INFO - propertiesFile          null
[2024-09-23T21:08:56.704-0300] {spark_submit.py:579} INFO - driverMemory            null
[2024-09-23T21:08:56.704-0300] {spark_submit.py:579} INFO - driverCores             null
[2024-09-23T21:08:56.705-0300] {spark_submit.py:579} INFO - driverExtraClassPath    null
[2024-09-23T21:08:56.705-0300] {spark_submit.py:579} INFO - driverExtraLibraryPath  null
[2024-09-23T21:08:56.705-0300] {spark_submit.py:579} INFO - driverExtraJavaOptions  null
[2024-09-23T21:08:56.705-0300] {spark_submit.py:579} INFO - supervise               false
[2024-09-23T21:08:56.706-0300] {spark_submit.py:579} INFO - queue                   root.default
[2024-09-23T21:08:56.706-0300] {spark_submit.py:579} INFO - numExecutors            null
[2024-09-23T21:08:56.706-0300] {spark_submit.py:579} INFO - files                   null
[2024-09-23T21:08:56.706-0300] {spark_submit.py:579} INFO - pyFiles                 null
[2024-09-23T21:08:56.706-0300] {spark_submit.py:579} INFO - archives                null
[2024-09-23T21:08:56.706-0300] {spark_submit.py:579} INFO - mainClass               null
[2024-09-23T21:08:56.706-0300] {spark_submit.py:579} INFO - primaryResource         file:/home/thiagomares/Área%20de%20trabalho/fluxos_de_trabalho/include/teste.py
[2024-09-23T21:08:56.707-0300] {spark_submit.py:579} INFO - name                    spark_test_job
[2024-09-23T21:08:56.707-0300] {spark_submit.py:579} INFO - childArgs               []
[2024-09-23T21:08:56.707-0300] {spark_submit.py:579} INFO - jars                    null
[2024-09-23T21:08:56.707-0300] {spark_submit.py:579} INFO - packages                null
[2024-09-23T21:08:56.707-0300] {spark_submit.py:579} INFO - packagesExclusions      null
[2024-09-23T21:08:56.707-0300] {spark_submit.py:579} INFO - repositories            null
[2024-09-23T21:08:56.707-0300] {spark_submit.py:579} INFO - verbose                 true
[2024-09-23T21:08:56.707-0300] {spark_submit.py:579} INFO - 
[2024-09-23T21:08:56.707-0300] {spark_submit.py:579} INFO - Spark properties used, including those specified through
[2024-09-23T21:08:56.708-0300] {spark_submit.py:579} INFO - --conf and those from the properties file null:
[2024-09-23T21:08:56.708-0300] {spark_submit.py:579} INFO - 
[2024-09-23T21:08:56.708-0300] {spark_submit.py:579} INFO - 
[2024-09-23T21:08:56.708-0300] {spark_submit.py:579} INFO - 
[2024-09-23T21:08:57.018-0300] {spark_submit.py:579} INFO - Main class:
[2024-09-23T21:08:57.018-0300] {spark_submit.py:579} INFO - org.apache.spark.deploy.PythonRunner
[2024-09-23T21:08:57.018-0300] {spark_submit.py:579} INFO - Arguments:
[2024-09-23T21:08:57.019-0300] {spark_submit.py:579} INFO - file:/home/thiagomares/Área%20de%20trabalho/fluxos_de_trabalho/include/teste.py
[2024-09-23T21:08:57.019-0300] {spark_submit.py:579} INFO - null
[2024-09-23T21:08:57.024-0300] {spark_submit.py:579} INFO - Spark config:
[2024-09-23T21:08:57.024-0300] {spark_submit.py:579} INFO - (spark.app.name,spark_test_job)
[2024-09-23T21:08:57.024-0300] {spark_submit.py:579} INFO - (spark.app.submitTime,1727136536989)
[2024-09-23T21:08:57.025-0300] {spark_submit.py:579} INFO - (spark.master,spark://192.168.18.10:7077)
[2024-09-23T21:08:57.025-0300] {spark_submit.py:579} INFO - (spark.submit.deployMode,client)
[2024-09-23T21:08:57.025-0300] {spark_submit.py:579} INFO - (spark.submit.pyFiles,)
[2024-09-23T21:08:57.025-0300] {spark_submit.py:579} INFO - Classpath elements:
[2024-09-23T21:08:57.025-0300] {spark_submit.py:579} INFO - 
[2024-09-23T21:08:57.025-0300] {spark_submit.py:579} INFO - 
[2024-09-23T21:08:57.025-0300] {spark_submit.py:579} INFO - 
[2024-09-23T21:08:57.617-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO SparkContext: Running Spark version 3.5.2
[2024-09-23T21:08:57.619-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO SparkContext: OS info Linux, 6.8.0-45-generic, amd64
[2024-09-23T21:08:57.620-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO SparkContext: Java version 21.0.4
[2024-09-23T21:08:57.671-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-23T21:08:57.754-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO ResourceUtils: ==============================================================
[2024-09-23T21:08:57.754-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-09-23T21:08:57.755-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO ResourceUtils: ==============================================================
[2024-09-23T21:08:57.755-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO SparkContext: Submitted application: ExportarParaParquet
[2024-09-23T21:08:57.775-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-09-23T21:08:57.782-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO ResourceProfile: Limiting resource is cpu
[2024-09-23T21:08:57.783-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-09-23T21:08:57.835-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO SecurityManager: Changing view acls to: thiagomares
[2024-09-23T21:08:57.836-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO SecurityManager: Changing modify acls to: thiagomares
[2024-09-23T21:08:57.836-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO SecurityManager: Changing view acls groups to:
[2024-09-23T21:08:57.837-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO SecurityManager: Changing modify acls groups to:
[2024-09-23T21:08:57.837-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:57 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: thiagomares; groups with view permissions: EMPTY; users with modify permissions: thiagomares; groups with modify permissions: EMPTY
[2024-09-23T21:08:58.073-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO Utils: Successfully started service 'sparkDriver' on port 35893.
[2024-09-23T21:08:58.116-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO SparkEnv: Registering MapOutputTracker
[2024-09-23T21:08:58.161-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO SparkEnv: Registering BlockManagerMaster
[2024-09-23T21:08:58.188-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-09-23T21:08:58.188-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-09-23T21:08:58.195-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-09-23T21:08:58.224-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-681f3dc8-d329-4312-966e-2e9eaaa41dfa
[2024-09-23T21:08:58.242-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-09-23T21:08:58.260-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-09-23T21:08:58.379-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO JettyUtils: Start Jetty 192.168.18.10:4040 for SparkUI
[2024-09-23T21:08:58.436-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-09-23T21:08:58.564-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://192.168.18.10:7077...
[2024-09-23T21:08:58.610-0300] {spark_submit.py:579} INFO - 24/09/23 21:08:58 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 192.168.18.10:7077
[2024-09-23T21:08:58.611-0300] {spark_submit.py:579} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-09-23T21:08:58.611-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-09-23T21:08:58.611-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-09-23T21:08:58.611-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-09-23T21:08:58.611-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-09-23T21:08:58.611-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-09-23T21:08:58.611-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - Caused by: java.io.IOException: Failed to connect to /192.168.18.10:7077
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-09-23T21:08:58.612-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - ... 4 more
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Conexão recusada: /192.168.18.10:7077
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - Caused by: java.net.ConnectException: Conexão recusada
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-09-23T21:08:58.613-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-09-23T21:08:58.614-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-09-23T21:08:58.614-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-09-23T21:08:58.614-0300] {spark_submit.py:579} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-09-23T21:08:58.614-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-09-23T21:08:58.614-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-09-23T21:09:15.272-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:15 WARN GarbageCollectionMetrics: To enable non-built-in garbage collector(s) List(G1 Concurrent GC), users should configure it(them) to spark.eventLog.gcMetrics.youngGenerationGarbageCollectors or spark.eventLog.gcMetrics.oldGenerationGarbageCollectors
[2024-09-23T21:09:18.564-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:18 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://192.168.18.10:7077...
[2024-09-23T21:09:18.567-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:18 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 192.168.18.10:7077
[2024-09-23T21:09:18.567-0300] {spark_submit.py:579} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-09-23T21:09:18.568-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-09-23T21:09:18.569-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-09-23T21:09:18.569-0300] {spark_submit.py:579} INFO - Caused by: java.io.IOException: Failed to connect to /192.168.18.10:7077
[2024-09-23T21:09:18.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-09-23T21:09:18.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-09-23T21:09:18.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-09-23T21:09:18.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-09-23T21:09:18.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-09-23T21:09:18.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-09-23T21:09:18.570-0300] {spark_submit.py:579} INFO - ... 4 more
[2024-09-23T21:09:18.570-0300] {spark_submit.py:579} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Conexão recusada: /192.168.18.10:7077
[2024-09-23T21:09:18.570-0300] {spark_submit.py:579} INFO - Caused by: java.net.ConnectException: Conexão recusada
[2024-09-23T21:09:18.570-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-09-23T21:09:18.570-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
[2024-09-23T21:09:18.570-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
[2024-09-23T21:09:18.570-0300] {spark_submit.py:579} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-09-23T21:09:18.570-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-09-23T21:09:18.571-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-09-23T21:09:18.571-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-09-23T21:09:18.571-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-09-23T21:09:18.571-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-09-23T21:09:18.571-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-09-23T21:09:18.571-0300] {spark_submit.py:579} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-09-23T21:09:18.571-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-09-23T21:09:18.571-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-09-23T21:09:38.564-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:38 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://192.168.18.10:7077...
[2024-09-23T21:09:38.567-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:38 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 192.168.18.10:7077
[2024-09-23T21:09:38.568-0300] {spark_submit.py:579} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-09-23T21:09:38.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-09-23T21:09:38.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-09-23T21:09:38.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-09-23T21:09:38.568-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - Caused by: java.io.IOException: Failed to connect to /192.168.18.10:7077
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-09-23T21:09:38.569-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - ... 4 more
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Conexão recusada: /192.168.18.10:7077
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - Caused by: java.net.ConnectException: Conexão recusada
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
[2024-09-23T21:09:38.570-0300] {spark_submit.py:579} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-09-23T21:09:38.571-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-09-23T21:09:38.571-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-09-23T21:09:38.571-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-09-23T21:09:38.571-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-09-23T21:09:38.571-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-09-23T21:09:38.571-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-09-23T21:09:38.571-0300] {spark_submit.py:579} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-09-23T21:09:38.571-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-09-23T21:09:38.571-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-09-23T21:09:58.566-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-09-23T21:09:58.566-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-09-23T21:09:58.577-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36473.
[2024-09-23T21:09:58.577-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 INFO NettyBlockTransferService: Server created on 192.168.18.10:36473
[2024-09-23T21:09:58.580-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-09-23T21:09:58.592-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.168.18.10, 36473, None)
[2024-09-23T21:09:58.596-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.18.10:36473 with 434.4 MiB RAM, BlockManagerId(driver, 192.168.18.10, 36473, None)
[2024-09-23T21:09:58.598-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.168.18.10, 36473, None)
[2024-09-23T21:09:58.600-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 192.168.18.10, 36473, None)
[2024-09-23T21:09:58.866-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:58 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-09-23T21:09:59.109-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-09-23T21:09:59.121-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO SparkUI: Stopped Spark web UI at http://192.168.18.10:4040
[2024-09-23T21:09:59.125-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-09-23T21:09:59.128-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-09-23T21:09:59.132-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2024-09-23T21:09:59.140-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-09-23T21:09:59.152-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO MemoryStore: MemoryStore cleared
[2024-09-23T21:09:59.153-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO BlockManager: BlockManager stopped
[2024-09-23T21:09:59.158-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-09-23T21:09:59.163-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-09-23T21:09:59.170-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO SparkContext: Successfully stopped SparkContext
[2024-09-23T21:09:59.180-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-09-23T21:09:59.189-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO SharedState: Warehouse path is 'file:/home/thiagomares/Área%20de%20trabalho/fluxos_de_trabalho/spark-warehouse'.
[2024-09-23T21:09:59.236-0300] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-09-23T21:09:59.236-0300] {spark_submit.py:579} INFO - File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/include/teste.py", line 26, in <module>
[2024-09-23T21:09:59.236-0300] {spark_submit.py:579} INFO - main()
[2024-09-23T21:09:59.236-0300] {spark_submit.py:579} INFO - File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/include/teste.py", line 13, in main
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - df = spark.createDataFrame(data, columns)
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1443, in createDataFrame
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1485, in _create_dataframe
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1093, in _createFromLocal
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 952, in _inferSchemaFromList
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 624, in _jconf
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-09-23T21:09:59.237-0300] {spark_submit.py:579} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o23.sessionState.
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - : java.lang.IllegalStateException: LiveListenerBus is stopped.
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.LiveListenerBus.addToQueue(LiveListenerBus.scala:92)
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.LiveListenerBus.addToStatusQueue(LiveListenerBus.scala:75)
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:115)
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - at org.apache.spark.sql.SparkSession.$anonfun$sharedState$1(SparkSession.scala:143)
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:143)
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:142)
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:162)
[2024-09-23T21:09:59.238-0300] {spark_submit.py:579} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:160)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:157)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:75)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-09-23T21:09:59.239-0300] {spark_submit.py:579} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-09-23T21:09:59.240-0300] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-09-23T21:09:59.240-0300] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-09-23T21:09:59.240-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-09-23T21:09:59.240-0300] {spark_submit.py:579} INFO - 
[2024-09-23T21:09:59.299-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO ShutdownHookManager: Shutdown hook called
[2024-09-23T21:09:59.300-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO ShutdownHookManager: Deleting directory /tmp/spark-3143ba89-48b0-46cc-9aa3-909671f7c84e/pyspark-c1267ceb-7c33-44fa-bab1-5d861653dc99
[2024-09-23T21:09:59.304-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO ShutdownHookManager: Deleting directory /tmp/spark-3143ba89-48b0-46cc-9aa3-909671f7c84e
[2024-09-23T21:09:59.307-0300] {spark_submit.py:579} INFO - 24/09/23 21:09:59 INFO ShutdownHookManager: Deleting directory /tmp/spark-7d9d64b0-21a7-4224-9eee-45dcb036612d
[2024-09-23T21:09:59.363-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://192.168.18.10:7077 --name spark_test_job --verbose --queue root.default --deploy-mode client ./include/teste.py. Error code is: 1.
[2024-09-23T21:09:59.369-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_test_dag, task_id=run_spark_job, run_id=scheduled__2024-09-23T00:00:00+00:00, execution_date=20240923T000000, start_date=20240924T000855, end_date=20240924T000959
[2024-09-23T21:09:59.386-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-23T21:09:59.387-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task run_spark_job (Cannot execute: spark-submit --master spark://192.168.18.10:7077 --name spark_test_job --verbose --queue root.default --deploy-mode client ./include/teste.py. Error code is: 1.; 30223)
Traceback (most recent call last):
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/thiagomares/Área de trabalho/fluxos_de_trabalho/.venv/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://192.168.18.10:7077 --name spark_test_job --verbose --queue root.default --deploy-mode client ./include/teste.py. Error code is: 1.
[2024-09-23T21:09:59.413-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-23T21:09:59.427-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-23T21:09:59.427-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
